// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deliveryMgmt/deliverypb/delivery.proto

package deliverypb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeliveryBoy struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating               string    `protobuf:"bytes,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Location             *Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeliveryBoy) Reset()         { *m = DeliveryBoy{} }
func (m *DeliveryBoy) String() string { return proto.CompactTextString(m) }
func (*DeliveryBoy) ProtoMessage()    {}
func (*DeliveryBoy) Descriptor() ([]byte, []int) {
	return fileDescriptor_896a9196b599b1d4, []int{0}
}

func (m *DeliveryBoy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryBoy.Unmarshal(m, b)
}
func (m *DeliveryBoy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryBoy.Marshal(b, m, deterministic)
}
func (m *DeliveryBoy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryBoy.Merge(m, src)
}
func (m *DeliveryBoy) XXX_Size() int {
	return xxx_messageInfo_DeliveryBoy.Size(m)
}
func (m *DeliveryBoy) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryBoy.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryBoy proto.InternalMessageInfo

func (m *DeliveryBoy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeliveryBoy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeliveryBoy) GetRating() string {
	if m != nil {
		return m.Rating
	}
	return ""
}

func (m *DeliveryBoy) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type OrderDetails struct {
	Orderid              string    `protobuf:"bytes,1,opt,name=orderid,proto3" json:"orderid,omitempty"`
	RestaurantLocation   *Location `protobuf:"bytes,2,opt,name=restaurantLocation,proto3" json:"restaurantLocation,omitempty"`
	DeliveryLocation     *Location `protobuf:"bytes,3,opt,name=deliveryLocation,proto3" json:"deliveryLocation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OrderDetails) Reset()         { *m = OrderDetails{} }
func (m *OrderDetails) String() string { return proto.CompactTextString(m) }
func (*OrderDetails) ProtoMessage()    {}
func (*OrderDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_896a9196b599b1d4, []int{1}
}

func (m *OrderDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetails.Unmarshal(m, b)
}
func (m *OrderDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetails.Marshal(b, m, deterministic)
}
func (m *OrderDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetails.Merge(m, src)
}
func (m *OrderDetails) XXX_Size() int {
	return xxx_messageInfo_OrderDetails.Size(m)
}
func (m *OrderDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetails.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetails proto.InternalMessageInfo

func (m *OrderDetails) GetOrderid() string {
	if m != nil {
		return m.Orderid
	}
	return ""
}

func (m *OrderDetails) GetRestaurantLocation() *Location {
	if m != nil {
		return m.RestaurantLocation
	}
	return nil
}

func (m *OrderDetails) GetDeliveryLocation() *Location {
	if m != nil {
		return m.DeliveryLocation
	}
	return nil
}

type Location struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_896a9196b599b1d4, []int{2}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type CreateDeliveryBoyRequest struct {
	Emp                  *DeliveryBoy `protobuf:"bytes,1,opt,name=emp,proto3" json:"emp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateDeliveryBoyRequest) Reset()         { *m = CreateDeliveryBoyRequest{} }
func (m *CreateDeliveryBoyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeliveryBoyRequest) ProtoMessage()    {}
func (*CreateDeliveryBoyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_896a9196b599b1d4, []int{3}
}

func (m *CreateDeliveryBoyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeliveryBoyRequest.Unmarshal(m, b)
}
func (m *CreateDeliveryBoyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeliveryBoyRequest.Marshal(b, m, deterministic)
}
func (m *CreateDeliveryBoyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeliveryBoyRequest.Merge(m, src)
}
func (m *CreateDeliveryBoyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeliveryBoyRequest.Size(m)
}
func (m *CreateDeliveryBoyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeliveryBoyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeliveryBoyRequest proto.InternalMessageInfo

func (m *CreateDeliveryBoyRequest) GetEmp() *DeliveryBoy {
	if m != nil {
		return m.Emp
	}
	return nil
}

type CreateDeliveryBoyResponse struct {
	Emp                  *DeliveryBoy `protobuf:"bytes,1,opt,name=emp,proto3" json:"emp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateDeliveryBoyResponse) Reset()         { *m = CreateDeliveryBoyResponse{} }
func (m *CreateDeliveryBoyResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDeliveryBoyResponse) ProtoMessage()    {}
func (*CreateDeliveryBoyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_896a9196b599b1d4, []int{4}
}

func (m *CreateDeliveryBoyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeliveryBoyResponse.Unmarshal(m, b)
}
func (m *CreateDeliveryBoyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeliveryBoyResponse.Marshal(b, m, deterministic)
}
func (m *CreateDeliveryBoyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeliveryBoyResponse.Merge(m, src)
}
func (m *CreateDeliveryBoyResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDeliveryBoyResponse.Size(m)
}
func (m *CreateDeliveryBoyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeliveryBoyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeliveryBoyResponse proto.InternalMessageInfo

func (m *CreateDeliveryBoyResponse) GetEmp() *DeliveryBoy {
	if m != nil {
		return m.Emp
	}
	return nil
}

type ReceiveOrederRequest struct {
	OrderDetails         *OrderDetails `protobuf:"bytes,1,opt,name=orderDetails,proto3" json:"orderDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReceiveOrederRequest) Reset()         { *m = ReceiveOrederRequest{} }
func (m *ReceiveOrederRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiveOrederRequest) ProtoMessage()    {}
func (*ReceiveOrederRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_896a9196b599b1d4, []int{5}
}

func (m *ReceiveOrederRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveOrederRequest.Unmarshal(m, b)
}
func (m *ReceiveOrederRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveOrederRequest.Marshal(b, m, deterministic)
}
func (m *ReceiveOrederRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveOrederRequest.Merge(m, src)
}
func (m *ReceiveOrederRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiveOrederRequest.Size(m)
}
func (m *ReceiveOrederRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveOrederRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveOrederRequest proto.InternalMessageInfo

func (m *ReceiveOrederRequest) GetOrderDetails() *OrderDetails {
	if m != nil {
		return m.OrderDetails
	}
	return nil
}

type ReceiveOrederResponse struct {
	DeliveryBoy          *DeliveryBoy `protobuf:"bytes,1,opt,name=deliveryBoy,proto3" json:"deliveryBoy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReceiveOrederResponse) Reset()         { *m = ReceiveOrederResponse{} }
func (m *ReceiveOrederResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiveOrederResponse) ProtoMessage()    {}
func (*ReceiveOrederResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_896a9196b599b1d4, []int{6}
}

func (m *ReceiveOrederResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveOrederResponse.Unmarshal(m, b)
}
func (m *ReceiveOrederResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveOrederResponse.Marshal(b, m, deterministic)
}
func (m *ReceiveOrederResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveOrederResponse.Merge(m, src)
}
func (m *ReceiveOrederResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiveOrederResponse.Size(m)
}
func (m *ReceiveOrederResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveOrederResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveOrederResponse proto.InternalMessageInfo

func (m *ReceiveOrederResponse) GetDeliveryBoy() *DeliveryBoy {
	if m != nil {
		return m.DeliveryBoy
	}
	return nil
}

type GetAllDeliveryBoysRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllDeliveryBoysRequest) Reset()         { *m = GetAllDeliveryBoysRequest{} }
func (m *GetAllDeliveryBoysRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllDeliveryBoysRequest) ProtoMessage()    {}
func (*GetAllDeliveryBoysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_896a9196b599b1d4, []int{7}
}

func (m *GetAllDeliveryBoysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllDeliveryBoysRequest.Unmarshal(m, b)
}
func (m *GetAllDeliveryBoysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllDeliveryBoysRequest.Marshal(b, m, deterministic)
}
func (m *GetAllDeliveryBoysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllDeliveryBoysRequest.Merge(m, src)
}
func (m *GetAllDeliveryBoysRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllDeliveryBoysRequest.Size(m)
}
func (m *GetAllDeliveryBoysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllDeliveryBoysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllDeliveryBoysRequest proto.InternalMessageInfo

type GetAllDeliveryBoysResponse struct {
	DeliveryBoy          *DeliveryBoy `protobuf:"bytes,1,opt,name=deliveryBoy,proto3" json:"deliveryBoy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetAllDeliveryBoysResponse) Reset()         { *m = GetAllDeliveryBoysResponse{} }
func (m *GetAllDeliveryBoysResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllDeliveryBoysResponse) ProtoMessage()    {}
func (*GetAllDeliveryBoysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_896a9196b599b1d4, []int{8}
}

func (m *GetAllDeliveryBoysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllDeliveryBoysResponse.Unmarshal(m, b)
}
func (m *GetAllDeliveryBoysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllDeliveryBoysResponse.Marshal(b, m, deterministic)
}
func (m *GetAllDeliveryBoysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllDeliveryBoysResponse.Merge(m, src)
}
func (m *GetAllDeliveryBoysResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllDeliveryBoysResponse.Size(m)
}
func (m *GetAllDeliveryBoysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllDeliveryBoysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllDeliveryBoysResponse proto.InternalMessageInfo

func (m *GetAllDeliveryBoysResponse) GetDeliveryBoy() *DeliveryBoy {
	if m != nil {
		return m.DeliveryBoy
	}
	return nil
}

func init() {
	proto.RegisterType((*DeliveryBoy)(nil), "deliveryMgmt.DeliveryBoy")
	proto.RegisterType((*OrderDetails)(nil), "deliveryMgmt.OrderDetails")
	proto.RegisterType((*Location)(nil), "deliveryMgmt.Location")
	proto.RegisterType((*CreateDeliveryBoyRequest)(nil), "deliveryMgmt.CreateDeliveryBoyRequest")
	proto.RegisterType((*CreateDeliveryBoyResponse)(nil), "deliveryMgmt.CreateDeliveryBoyResponse")
	proto.RegisterType((*ReceiveOrederRequest)(nil), "deliveryMgmt.ReceiveOrederRequest")
	proto.RegisterType((*ReceiveOrederResponse)(nil), "deliveryMgmt.ReceiveOrederResponse")
	proto.RegisterType((*GetAllDeliveryBoysRequest)(nil), "deliveryMgmt.GetAllDeliveryBoysRequest")
	proto.RegisterType((*GetAllDeliveryBoysResponse)(nil), "deliveryMgmt.GetAllDeliveryBoysResponse")
}

func init() {
	proto.RegisterFile("deliveryMgmt/deliverypb/delivery.proto", fileDescriptor_896a9196b599b1d4)
}

var fileDescriptor_896a9196b599b1d4 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x5f, 0x8b, 0xd3, 0x40,
	0x14, 0xc5, 0x49, 0xba, 0xac, 0xdd, 0x9b, 0xf8, 0xef, 0xa2, 0x4b, 0x1a, 0x7d, 0x58, 0x46, 0x58,
	0x0b, 0x42, 0x95, 0xf8, 0x28, 0x08, 0xd6, 0xe2, 0xfa, 0xa0, 0x2c, 0x44, 0x11, 0xf5, 0x6d, 0xb6,
	0x73, 0x29, 0x03, 0x69, 0x26, 0x4e, 0xa6, 0x85, 0x7d, 0xf0, 0x5b, 0xf9, 0xe8, 0x87, 0x93, 0x9d,
	0x26, 0xe9, 0xa4, 0x4d, 0x5b, 0x84, 0x7d, 0x9b, 0x3b, 0xf7, 0xdc, 0xdf, 0x3d, 0xed, 0x09, 0x03,
	0xe7, 0x82, 0x32, 0xb9, 0x24, 0x7d, 0xfd, 0x79, 0x36, 0x37, 0x2f, 0xeb, 0xa2, 0xb8, 0x6a, 0x8e,
	0xa3, 0x42, 0x2b, 0xa3, 0x30, 0x74, 0x75, 0xec, 0x37, 0x04, 0x93, 0xaa, 0x1e, 0xab, 0x6b, 0xbc,
	0x07, 0xbe, 0x14, 0x91, 0x77, 0xe6, 0x0d, 0x4f, 0x52, 0x5f, 0x0a, 0x44, 0x38, 0xca, 0xf9, 0x9c,
	0x22, 0xdf, 0xde, 0xd8, 0x33, 0x9e, 0xc2, 0xb1, 0xe6, 0x46, 0xe6, 0xb3, 0xa8, 0x67, 0x6f, 0xab,
	0x0a, 0x13, 0xe8, 0x67, 0x6a, 0xca, 0x8d, 0x54, 0x79, 0x74, 0x74, 0xe6, 0x0d, 0x83, 0xe4, 0x74,
	0xe4, 0xee, 0x1a, 0x7d, 0xaa, 0xba, 0x69, 0xa3, 0x63, 0x7f, 0x3c, 0x08, 0x2f, 0xb5, 0x20, 0x3d,
	0x21, 0xc3, 0x65, 0x56, 0x62, 0x04, 0x77, 0xd4, 0x4d, 0xdd, 0xb8, 0xa8, 0x4b, 0xfc, 0x00, 0xa8,
	0xa9, 0x34, 0x7c, 0xa1, 0x79, 0x6e, 0x6a, 0x94, 0x35, 0xb6, 0x7b, 0x51, 0xc7, 0x04, 0x8e, 0xe1,
	0x41, 0x2d, 0x6e, 0x28, 0xbd, 0xbd, 0x94, 0x2d, 0x3d, 0x9b, 0x40, 0xbf, 0xe1, 0xc5, 0xd0, 0xcf,
	0xb8, 0x91, 0x66, 0x21, 0xc8, 0x5a, 0xf6, 0xd3, 0xa6, 0xc6, 0xa7, 0x70, 0x92, 0xa9, 0x7c, 0xb6,
	0x6a, 0xfa, 0xb6, 0xb9, 0xbe, 0x60, 0x17, 0x10, 0xbd, 0xd7, 0xc4, 0x0d, 0x39, 0x09, 0xa4, 0xf4,
	0x6b, 0x41, 0xa5, 0xc1, 0x17, 0xd0, 0xa3, 0x79, 0x61, 0x81, 0x41, 0x32, 0x68, 0x1b, 0x73, 0xe5,
	0x37, 0x2a, 0xf6, 0x11, 0x06, 0x1d, 0xa0, 0xb2, 0x50, 0x79, 0x49, 0xff, 0x47, 0xfa, 0x06, 0x8f,
	0x52, 0x9a, 0x92, 0x5c, 0xd2, 0xa5, 0x26, 0x41, 0xba, 0xb6, 0xf3, 0x16, 0x42, 0xe5, 0xc4, 0x54,
	0xd1, 0xe2, 0x36, 0xcd, 0x0d, 0x32, 0x6d, 0xe9, 0xd9, 0x57, 0x78, 0xbc, 0xc1, 0xad, 0xdc, 0xbd,
	0x81, 0x40, 0xac, 0x4d, 0x1c, 0x76, 0xe9, 0xaa, 0xd9, 0x13, 0x18, 0x5c, 0x90, 0x79, 0x97, 0x65,
	0x8e, 0xa2, 0xac, 0x2c, 0xb3, 0x1f, 0x10, 0x77, 0x35, 0x6f, 0x61, 0x6f, 0xf2, 0xd7, 0x87, 0xfb,
	0x75, 0xf3, 0x0b, 0xe9, 0xa5, 0x9c, 0x12, 0x0a, 0x78, 0xb8, 0x95, 0x01, 0x9e, 0xb7, 0x81, 0xbb,
	0xd2, 0x8e, 0x9f, 0x1f, 0xd4, 0x55, 0xb6, 0x25, 0xe0, 0xf6, 0x8f, 0xc2, 0x8d, 0xf1, 0x9d, 0xff,
	0x49, 0x3c, 0x3c, 0x2c, 0x5c, 0x2d, 0x7a, 0xe5, 0xe1, 0x77, 0xb8, 0xdb, 0x8a, 0x0c, 0x59, 0x7b,
	0xb8, 0xeb, 0x3b, 0x89, 0x9f, 0xed, 0xd5, 0xac, 0xd8, 0xe3, 0xf0, 0x27, 0xac, 0x9f, 0xa7, 0xab,
	0x63, 0xfb, 0x2c, 0xbd, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x69, 0xf8, 0xdf, 0xc0, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeliveryServiceClient is the client API for DeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeliveryServiceClient interface {
	CreateDeliveryBoy(ctx context.Context, in *CreateDeliveryBoyRequest, opts ...grpc.CallOption) (*CreateDeliveryBoyResponse, error)
	GetAllDeliveryBoys(ctx context.Context, in *GetAllDeliveryBoysRequest, opts ...grpc.CallOption) (DeliveryService_GetAllDeliveryBoysClient, error)
	ReceiveOreder(ctx context.Context, in *ReceiveOrederRequest, opts ...grpc.CallOption) (*ReceiveOrederResponse, error)
}

type deliveryServiceClient struct {
	cc *grpc.ClientConn
}

func NewDeliveryServiceClient(cc *grpc.ClientConn) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) CreateDeliveryBoy(ctx context.Context, in *CreateDeliveryBoyRequest, opts ...grpc.CallOption) (*CreateDeliveryBoyResponse, error) {
	out := new(CreateDeliveryBoyResponse)
	err := c.cc.Invoke(ctx, "/deliveryMgmt.DeliveryService/CreateDeliveryBoy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetAllDeliveryBoys(ctx context.Context, in *GetAllDeliveryBoysRequest, opts ...grpc.CallOption) (DeliveryService_GetAllDeliveryBoysClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DeliveryService_serviceDesc.Streams[0], "/deliveryMgmt.DeliveryService/GetAllDeliveryBoys", opts...)
	if err != nil {
		return nil, err
	}
	x := &deliveryServiceGetAllDeliveryBoysClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DeliveryService_GetAllDeliveryBoysClient interface {
	Recv() (*GetAllDeliveryBoysResponse, error)
	grpc.ClientStream
}

type deliveryServiceGetAllDeliveryBoysClient struct {
	grpc.ClientStream
}

func (x *deliveryServiceGetAllDeliveryBoysClient) Recv() (*GetAllDeliveryBoysResponse, error) {
	m := new(GetAllDeliveryBoysResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *deliveryServiceClient) ReceiveOreder(ctx context.Context, in *ReceiveOrederRequest, opts ...grpc.CallOption) (*ReceiveOrederResponse, error) {
	out := new(ReceiveOrederResponse)
	err := c.cc.Invoke(ctx, "/deliveryMgmt.DeliveryService/ReceiveOreder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryServiceServer is the server API for DeliveryService service.
type DeliveryServiceServer interface {
	CreateDeliveryBoy(context.Context, *CreateDeliveryBoyRequest) (*CreateDeliveryBoyResponse, error)
	GetAllDeliveryBoys(*GetAllDeliveryBoysRequest, DeliveryService_GetAllDeliveryBoysServer) error
	ReceiveOreder(context.Context, *ReceiveOrederRequest) (*ReceiveOrederResponse, error)
}

// UnimplementedDeliveryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeliveryServiceServer struct {
}

func (*UnimplementedDeliveryServiceServer) CreateDeliveryBoy(ctx context.Context, req *CreateDeliveryBoyRequest) (*CreateDeliveryBoyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeliveryBoy not implemented")
}
func (*UnimplementedDeliveryServiceServer) GetAllDeliveryBoys(req *GetAllDeliveryBoysRequest, srv DeliveryService_GetAllDeliveryBoysServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllDeliveryBoys not implemented")
}
func (*UnimplementedDeliveryServiceServer) ReceiveOreder(ctx context.Context, req *ReceiveOrederRequest) (*ReceiveOrederResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveOreder not implemented")
}

func RegisterDeliveryServiceServer(s *grpc.Server, srv DeliveryServiceServer) {
	s.RegisterService(&_DeliveryService_serviceDesc, srv)
}

func _DeliveryService_CreateDeliveryBoy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeliveryBoyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).CreateDeliveryBoy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/deliveryMgmt.DeliveryService/CreateDeliveryBoy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).CreateDeliveryBoy(ctx, req.(*CreateDeliveryBoyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetAllDeliveryBoys_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllDeliveryBoysRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeliveryServiceServer).GetAllDeliveryBoys(m, &deliveryServiceGetAllDeliveryBoysServer{stream})
}

type DeliveryService_GetAllDeliveryBoysServer interface {
	Send(*GetAllDeliveryBoysResponse) error
	grpc.ServerStream
}

type deliveryServiceGetAllDeliveryBoysServer struct {
	grpc.ServerStream
}

func (x *deliveryServiceGetAllDeliveryBoysServer) Send(m *GetAllDeliveryBoysResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DeliveryService_ReceiveOreder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveOrederRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).ReceiveOreder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/deliveryMgmt.DeliveryService/ReceiveOreder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).ReceiveOreder(ctx, req.(*ReceiveOrederRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeliveryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "deliveryMgmt.DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeliveryBoy",
			Handler:    _DeliveryService_CreateDeliveryBoy_Handler,
		},
		{
			MethodName: "ReceiveOreder",
			Handler:    _DeliveryService_ReceiveOreder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllDeliveryBoys",
			Handler:       _DeliveryService_GetAllDeliveryBoys_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "deliveryMgmt/deliverypb/delivery.proto",
}
